In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (1.26.2)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.26.0 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd

In [5]:
books = pd.read_csv('C:/Users/RAO/Desktop/archive/Books.csv')
users = pd.read_csv('C:/Users/RAO/Desktop/archive/Users.csv')
ratings = pd.read_csv('C:/Users/RAO/Desktop/archive/Ratings.csv')

C:\Users\RAO\AppData\Local\Temp\ipykernel_16508\1423823446.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('C:/Users/RAO/Desktop/archive/Books.csv')

In [6]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [7]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [8]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [9]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [10]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [11]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [12]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [13]:
books.duplicated().sum()

0

In [14]:
ratings.duplicated().sum()

0

## Popularity Based Recommender System

In [15]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [16]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [17]:
print(ratings_with_name.columns)

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L'],
      dtype='object')

In [18]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_ratings'},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [19]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean(['Book-Rating']).reset_index()

In [20]:
ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')

In [21]:
ratings_with_name = ratings_with_name.dropna(subset=['Book-Rating'])

In [22]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean(['Book-Rating']).reset_index()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'},inplace=True)
avg_rating_df

,Book-Title,User-ID,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,51807.250000,2.250000
1,Always Have Popsicles,172742.000000,0.000000
2,Apple Magic (The Collector's series),198711.000000,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",269557.000000,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,11601.000000,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,100532.500000,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,116729.500000,5.250000
241068,Ã?Â?sterlich leben.,256636.000000,7.000000
241069,Ã?Â?stlich der Berge.,198497.333333,2.666667
241070,Ã?Â?thique en toc,39532.000000,4.000000

In [23]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_ratings,User-ID,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,51807.250000,2.250000
1,Always Have Popsicles,1,172742.000000,0.000000
2,Apple Magic (The Collector's series),1,198711.000000,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,269557.000000,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,11601.000000,0.000000
...,...,...,...,...
241066,Ã?Â?lpiraten.,2,100532.500000,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,116729.500000,5.250000
241068,Ã?Â?sterlich leben.,1,256636.000000,7.000000
241069,Ã?Â?stlich der Berge.,3,198497.333333,2.666667
241070,Ã?Â?thique en toc,2,39532.000000,4.000000

In [24]:
popular_df[popular_df['num_ratings']>=250]

,Book-Title,num_ratings,User-ID,avg_ratings
764,1984,284,138815.169014,4.454225
818,1st to Die: A Novel,509,144043.722986,3.575639
1048,2nd Chance,356,147263.241573,3.269663
1760,A Bend in the Road,346,140247.869942,3.364162
2281,"A Child Called \It\"": One Child's Courage to S...",265,130185.033962,4.086792
...,...,...,...,...
233850,White Oleander : A Novel,387,129316.811370,3.506460
233851,White Oleander : A Novel (Oprah's Book Club),356,138470.325843,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,141629.536810,3.766871
234951,Wild Animus,2502,140706.721423,1.019584
240860,"\O\"" Is for Outlaw""",269,146806.981413,2.988848

In [25]:
popular_df = popular_df[popular_df['num_ratings'] >= 250].sort_values('avg_ratings',ascending=False).head(50)
popular_df

,Book-Title,num_ratings,User-ID,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,140704.920561,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,149688.418605,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,139771.791367,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,144781.907781,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,137446.406475,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,143270.156584,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,135171.953804,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,139636.610435,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,133551.907692,4.880769
219741,To Kill a Mockingbird,510,137484.266667,4.700000
183573,The Da Vinci Code,898,136996.018931,4.642539
187880,The Five People You Meet in Heaven,430,135222.918605,4.551163
180556,The Catcher in the Rye,449,144511.893096,4.545657
196326,The Lovely Bones: A Novel,1295,140728.515830,4.468726
764,1984,284,138815.169014,4.454225
144165,Prodigal Summer: A Novel,253,141885.098814,4.450593
128670,Neverwhere,265,143746.969811,4.449057
206502,The Secret Life of Bees,774,138196.041344,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,133369.487633,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,144197.572008,4.354970
204387,The Red Tent (Bestselling Backlist),723,137838.575380,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,130204.817164,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,136196.743284,4.289552
93381,Into the Wild,252,138851.484127,4.273810
63867,Fahrenheit 451,409,137742.863081,4.264059
74750,Girl with a Pearl Earring,526,135773.948669,4.218631
136145,Outlander,283,136221.204947,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,138049.782906,4.105983
156102,Seabiscuit: An American Legend,275,137388.916364,4.098182
107962,Life of Pi,664,140203.996988,4.088855
176845,The Bean Trees,389,133392.758355,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,130185.033962,4.086792
8434,ANGELA'S ASHES,279,138811.885305,4.075269
76343,Good in Bed,490,136997.177551,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,140205.205607,4.037383
12700,American Gods,302,144888.211921,4.006623
161645,Skipping Christmas,322,137085.065217,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,133780.119497,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,143887.369048,4.000000
181679,The Color Purple,314,135980.283439,3.964968
160336,Silence of the Lambs,256,141374.417969,3.960938
8752,About a Boy,262,137275.171756,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,140992.485612,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,134910.154135,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,142077.561338,3.825279
170101,Suzanne's Diary for Nicholas,457,145548.982495,3.820569
111073,Lord of the Flies,259,141221.420849,3.818533
5664,A Prayer for Owen Meany,413,138547.859564,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,146720.365449,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,138470.325843,3.772472

In [26]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_ratings','avg_ratings']]

In [27]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

In [28]:
print(popular_df.columns)

Index(['Book-Title', 'Book-Author', 'Image-URL-M', 'num_ratings',
       'avg_ratings'],
      dtype='object')

In [29]:
print(popular_df.head())

                                           Book-Title    Book-Author  \
0   Harry Potter and the Prisoner of Azkaban (Book 3)  J. K. Rowling
3        Harry Potter and the Goblet of Fire (Book 4)  J. K. Rowling
5      Harry Potter and the Sorcerer's Stone (Book 1)  J. K. Rowling
9   Harry Potter and the Order of the Phoenix (Boo...  J. K. Rowling
13   Harry Potter and the Chamber of Secrets (Book 2)  J. K. Rowling

                                          Image-URL-M  num_ratings  \
0   http://images.amazon.com/images/P/0439136350.0...          428
3   http://images.amazon.com/images/P/0439139597.0...          387
5   http://images.amazon.com/images/P/0590353403.0...          278
9   http://images.amazon.com/images/P/043935806X.0...          347
13  http://images.amazon.com/images/P/0439064872.0...          556

    avg_ratings
0      5.852804
3      5.824289
5      5.737410
9      5.501441
13     5.183453

## Collaborative Filtering Based Recommender System

In [30]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
padhe_likhe_users = x[x].index

In [31]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe_users)]

In [32]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [33]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books = y[y].index

In [34]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
pt = final_ratings.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [35]:
pt.fillna(0,inplace=True)

In [36]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [37]:
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.26.2)
Requirement already satisfied: scipy>=1.5.0 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\rao\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.2.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
from sklearn.metrics.pairwise import cosine_similarity

In [40]:
similarity_scores = cosine_similarity(pt)

In [41]:
similarity_scores.shape

(706, 706)

In [42]:
def recommend(book_name):
    #index fetch
     suggestions = []
     index = np.where(pt.index==book_name)[0][0]
     similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]

     for i in similar_items:
         suggestions.append(pt.index[i[0]])
     return suggestions

In [43]:
recommend('Zen and the Art of Motorcycle Maintenance: An Inquiry into Values')

['Prodigal Summer',
 'Pet Sematary',
 'Midnight',
 "The Hitchhiker's Guide to the Galaxy",
 'A Prayer for Owen Meany']

In [44]:
pt.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [46]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))